module main

fn test_no_matches() {
	candidates := ['hello', 'world', 'zombies', 'pants']
	expected := []string{}
	assert find_anagrams('diaper', candidates) == expected
}

fn test_detects_anagram() {
	candidates := ['enlists', 'google', 'inlets', 'banana']
	expected := ['inlets']
	assert find_anagrams('listen', candidates) == expected
}

fn test_detects_many_anagrams() {
	candidates := [
		'ZYXWVUTSRQPONMLKJIHGFEDCBA',
		'MNOPQRSTUVWXYZABCDEFGHIJKL',
		'BADCFEHGJILKNMPORQTSVUXWZY',
		'QWERTYUIOPASDFGHJKLZXCVBNM',
		'GHIJKLMNOPQRSTUVWXYZABCDEF',
		'STUVWXYZABCDEFGHIJKLMNOPQR',
		'DCBAEFGHIJKLMNOPQRSTUVWXYZ',
		'AZBYCXDWEVFUGTHSIRJQKPLOMN',
		'ZAYXBWCVDUESFTGRHQIPJOKLNM',
		'NMLKJIHGFEDCBAZYXWVUTSRQPO',
		'BDFHJLNPRTVXZACEGIKMOQSUWY',
		'YWUSQOMKIGECAXZVTRPNLJHFDB',
		'JKLMNOPQRSTUVWXYZABCDEFGHI',
		'PONMLKJIHGFEDCBAZYXWVUTSRQ',
		'LKJIHGFEDCBAZYXWVUTSRQPONM',
	]
	expected := [
		'ZYXWVUTSRQPONMLKJIHGFEDCBA',
		'MNOPQRSTUVWXYZABCDEFGHIJKL',
		'BADCFEHGJILKNMPORQTSVUXWZY',
		'QWERTYUIOPASDFGHJKLZXCVBNM',
		'GHIJKLMNOPQRSTUVWXYZABCDEF',
		'STUVWXYZABCDEFGHIJKLMNOPQR',
		'DCBAEFGHIJKLMNOPQRSTUVWXYZ',
		'AZBYCXDWEVFUGTHSIRJQKPLOMN',
		'ZAYXBWCVDUESFTGRHQIPJOKLNM',
		'NMLKJIHGFEDCBAZYXWVUTSRQPO',
		'BDFHJLNPRTVXZACEGIKMOQSUWY',
		'YWUSQOMKIGECAXZVTRPNLJHFDB',
		'JKLMNOPQRSTUVWXYZABCDEFGHI',
		'PONMLKJIHGFEDCBAZYXWVUTSRQ',
		'LKJIHGFEDCBAZYXWVUTSRQPONM',
	]
	assert find_anagrams('ABCDEFGHIJKLMNOPQRSTUVWXYZ', candidates) == expected
}
